const ACCESS_USER_KEY = 'ACCESS_USER'
const NOTIFICATIONS_KEY = 'NOTIFICATIONS'
const SETTINGS_KEY = 'SETTINGS'
const API_ENDPOINT = '/api'

export {
    ACCESS_USER_KEY,
    NOTIFICATIONS_KEY,
    SETTINGS_KEY,
    API_ENDPOINT,
}
